name: Actualizar Cotizaciones en BigQuery

on:
  schedule:
    - cron: "0 2 * * *"  # Todos los días a las 2 AM UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update_bigquery:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: |
          pip install google-api-python-client google-auth google-cloud-bigquery pandas

      - name: Crear credenciales JSON
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > credentials.json
          if [ ! -s credentials.json ]; then
            echo "Error: El archivo de credenciales está vacío" && exit 1
          else
            echo "El archivo de credenciales se creó correctamente."
          fi

      - name: Depuración: Mostrar Contenido del Archivo
        run: |
          head -n 5 credentials.json  # Muestra las primeras líneas del archivo (sin exponer secretos sensibles)

      - name: Ejecutar script de actualización
        run: python actualizar.py
