      - name: Crear credenciales JSON
        run: |
          if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
            echo "Error: El secreto GCP_CREDENTIALS está vacío o no está configurado." && exit 1
          fi
          echo "${{ secrets.GCP_CREDENTIALS }}" > credentials.json

      - name: Depurar credenciales JSON
        run: |
          echo "Contenido del archivo credentials.json:"
          cat credentials.json
